### ISSUE TITLE
Issues with certain api calls

### ISSUE THREAD

**Issue by kjain333** [srthkpthk/splitwise_api#1]
Create expense function is not returning the response it gets after making the API call and certain functions like add user to group are not passing options parameter it gets in its parameters to API request

**Comment by srthkpthk** [comment]
Hello , @kjain333 your issue has been recorded and is being worked on , thanks for using this package , if it helped you please consider giving it a like or star , thanks

**Comment by srthkpthk** [comment]
@kjain333 this is fixed
